#!/bin/bash
#
# Part of fireball iptables init script
#
# Author: Ilya Lebedev <ilya@lebedev.net>
# License: LGPL v2
#
############################################################################################################
# DNSMasq script hook
############################################################################################################
#
# Receives data from DNSMasq and updates dhcp leases set accordingly
#
# $1 - old/new/del flag
# $2 - mac address
# $3 - ip address
# $4 - host name
SET="dhcp_leases"

case "$1" in
 "add"|"old")
  ipset add -! $SET $3
  ;;
 "del")
  ipset del -! $SET $3
  ;;
esac
